import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, act } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

// --- Mocks ---

const mockNavigate = vi.fn();

vi.mock("react-router", () => ({
  useNavigate: () => mockNavigate,
  useOutletContext: () => ({ isSignedIn: true, userName: null, userId: null }),
}));

vi.mock("../../../components/Navbar", () => ({
  Navbar: () => <nav data-testid="navbar" />,
}));

vi.mock("../../../components/ui/Button", () => ({
  default: ({ children, ...props }: React.PropsWithChildren<Record<string, unknown>>) => (
    <button {...(props as React.ButtonHTMLAttributes<HTMLButtonElement>)}>{children}</button>
  ),
}));

// Capture onComplete so tests can invoke it
let capturedOnComplete: ((base64: string) => void) | undefined;
vi.mock("../../../components/upload", () => ({
  Upload: ({ onComplete }: { onComplete: (base64: string) => void }) => {
    capturedOnComplete = onComplete;
    return <div data-testid="upload-component" />;
  },
}));

// Stub lucide-react icons used by home.tsx
vi.mock("lucide-react", () => ({
  ArrowRight: () => <svg data-testid="icon-arrow-right" />,
  ArrowUpRight: () => <svg data-testid="icon-arrow-up-right" />,
  Clock: () => <svg data-testid="icon-clock" />,
  Layers: () => <svg data-testid="icon-layers" />,
}));

// Stub the route types module (generated by react-router)
vi.mock("../../../app/routes/+types/home", () => ({}), { virtual: true });

import Home, { meta } from "../../../app/routes/home";

describe("home.tsx – meta()", () => {
  it("returns an array", () => {
    const result = meta({} as Parameters<typeof meta>[0]);
    expect(Array.isArray(result)).toBe(true);
  });

  it("includes a title entry", () => {
    const result = meta({} as Parameters<typeof meta>[0]);
    const titleEntry = result.find((r) => "title" in r);
    expect(titleEntry).toBeDefined();
    expect((titleEntry as { title: string }).title).toBeTruthy();
  });

  it("includes a description meta entry", () => {
    const result = meta({} as Parameters<typeof meta>[0]);
    const descEntry = result.find(
      (r) => "name" in r && (r as { name: string }).name === "description"
    );
    expect(descEntry).toBeDefined();
  });
});

describe("home.tsx – Home component", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    capturedOnComplete = undefined;
  });

  it("renders without crashing", () => {
    render(<Home />);
  });

  it("renders the Navbar", () => {
    render(<Home />);
    expect(screen.getByTestId("navbar")).toBeInTheDocument();
  });

  it("renders the Upload component", () => {
    render(<Home />);
    expect(screen.getByTestId("upload-component")).toBeInTheDocument();
  });

  it("renders the hero heading", () => {
    render(<Home />);
    expect(
      screen.getByText(/build beautiful spaces at the speed of thought/i)
    ).toBeInTheDocument();
  });

  it("renders the 'Start Building' CTA link", () => {
    render(<Home />);
    expect(screen.getByText(/start building/i)).toBeInTheDocument();
  });

  it("renders the 'Watch Demo' button", () => {
    render(<Home />);
    expect(screen.getByText(/watch demo/i)).toBeInTheDocument();
  });

  it("renders the 'Upload your floor plan' heading", () => {
    render(<Home />);
    expect(screen.getByText(/upload your floor plan/i)).toBeInTheDocument();
  });

  it("renders the community projects section heading", () => {
    render(<Home />);
    expect(screen.getByRole("heading", { name: /^projects$/i })).toBeInTheDocument();
  });

  it("renders the 'Introducing Roomify 2.0' announcement", () => {
    render(<Home />);
    expect(screen.getByText(/introducing roomify 2\.0/i)).toBeInTheDocument();
  });

  describe("handleUploadComplete", () => {
    it("navigates to /Visualizer/:id when onComplete is called", async () => {
      render(<Home />);
      expect(capturedOnComplete).toBeDefined();

      await act(async () => {
        capturedOnComplete!("data:image/png;base64,abc123");
      });

      expect(mockNavigate).toHaveBeenCalledTimes(1);
      const navArg = mockNavigate.mock.calls[0][0] as string;
      expect(navArg).toMatch(/^\/Visualizer\/\d+$/);
    });

    it("uses a timestamp-based unique ID for navigation", async () => {
      const before = Date.now();
      render(<Home />);

      await act(async () => {
        capturedOnComplete!("data:image/png;base64,abc");
      });

      const navArg = mockNavigate.mock.calls[0][0] as string;
      const idPart = navArg.replace("/Visualizer/", "");
      const id = Number(idPart);
      const after = Date.now();

      expect(id).toBeGreaterThanOrEqual(before);
      expect(id).toBeLessThanOrEqual(after);
    });

    it("generates different IDs on successive calls", async () => {
      render(<Home />);

      const ids: string[] = [];

      for (let i = 0; i < 3; i++) {
        vi.clearAllMocks();
        // Advance time slightly between calls
        await new Promise((r) => setTimeout(r, 2));
        await act(async () => {
          capturedOnComplete!("data:image/png;base64,abc");
        });
        const navArg = mockNavigate.mock.calls[0][0] as string;
        ids.push(navArg.replace("/Visualizer/", ""));
      }

      const uniqueIds = new Set(ids);
      // At minimum the values should be numeric strings
      ids.forEach((id) => expect(id).toMatch(/^\d+$/));
      // They should be non-decreasing timestamps
      expect(Number(ids[1])).toBeGreaterThanOrEqual(Number(ids[0]));
    });

    it("passes onComplete as a function to the Upload component", () => {
      render(<Home />);
      expect(typeof capturedOnComplete).toBe("function");
    });
  });
});